### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by builderjer**
Allow for ovos_utils >0.1.0

### CODE REVIEW

**Review by mikejgray — CHANGES_REQUESTED** [review]
Using ~=0.0 continues to pin to the alpha versions. You're looking for something more like <0.2.0,>=0.0.33

Have the imports already been moved?

**Comment by builderjer** [comment]
There were no errors with the imports

**Comment by mikejgray** [comment]
Setting to >=0.2.0 allows 0.2.0, we want to keep it at 0.1.x so let's remove the equals on that one. And we've tested this in 0.0.33, 0.0.38, and 0.1.0?

**Comment by builderjer** [comment]
yes, tested with all mentioned versions, at least past the loading point

**Comment by j1nx** [comment]
Could this PR be the cause of why I do not see background images when pulling in all different latest dev versions?

If so, I might be able to test this.

**Comment by mikejgray** [comment]
> Could this PR be the cause of why I do not see background images when pulling in all different latest dev versions?
> 
> If so, I might be able to test this.

Could be! Worth a shot.

**Review by JarbasAl — APPROVED** [review]

**Pull request merged**
